let users = [{ "id": 1, "name": "Lemuel", "email": "lwisniowski0@eepurl.com", "gender": "Male" },
{ "id": 2, "name": "Maurits", "email": "minett1@xrea.com", "gender": "Male" },
{ "id": 3, "name": "Cleavland", "email": "ctolman2@si.edu", "gender": "Male" },
{ "id": 4, "name": "Tracie", "email": "tcornell3@sourceforge.net", "gender": "Female" },
{ "id": 5, "name": "Peter", "email": "ppieche4@livejournal.com", "gender": "Male" },
{ "id": 6, "name": "Lisa", "email": "lyantsurev5@examiner.com", "gender": "Female" },
{ "id": 7, "name": "Angeli", "email": "ahamblin6@hibu.com", "gender": "Male" },
{ "id": 8, "name": "Kacey", "email": "ksynan7@europa.eu", "gender": "Female" },
{ "id": 9, "name": "Godwin", "email": "gdunsmuir8@mashable.com", "gender": "Male" },
{ "id": 10, "name": "Jinny", "email": "jtorres9@xrea.com", "gender": "Female" },
{ "id": 11, "name": "Lilyan", "email": "lniasa@ebay.com", "gender": "Female" },
{ "id": 12, "name": "Carlen", "email": "cmaccreab@smh.com.au", "gender": "Female" },
{ "id": 13, "name": "Leandra", "email": "ledneyc@rediff.com", "gender": "Female" },
{ "id": 14, "name": "Trev", "email": "tgliddend@xing.com", "gender": "Male" },
{ "id": 15, "name": "Berk", "email": "bgronave@google.ca", "gender": "Male" },
{ "id": 16, "name": "Berrie", "email": "bmeritf@imgur.com", "gender": "Female" },
{ "id": 17, "name": "Marc", "email": "mskellyg@columbia.edu", "gender": "Male" },
{ "id": 18, "name": "Antonius", "email": "ahallardh@gov.uk", "gender": "Male" },
{ "id": 19, "name": "Damian", "email": "dredferni@usda.gov", "gender": "Male" },
{ "id": 20, "name": "Norene", "email": "nlauj@addthis.com", "gender": "Female" },
{ "id": 21, "name": "Reider", "email": "rrealffk@utexas.edu", "gender": "Male" },
{ "id": 22, "name": "Hillary", "email": "hmccafferyl@tinyurl.com", "gender": "Male" },
{ "id": 23, "name": "Garland", "email": "gnovotnam@vkontakte.ru", "gender": "Female" },
{ "id": 24, "name": "Erminie", "email": "eseelyn@mac.com", "gender": "Female" },
{ "id": 25, "name": "Pier", "email": "pmcdirmido@posterous.com", "gender": "Female" },
{ "id": 26, "name": "Letisha", "email": "lgabbetisp@devhub.com", "gender": "Female" },
{ "id": 27, "name": "Adriana", "email": "aboysq@yelp.com", "gender": "Female" },
{ "id": 28, "name": "Norene", "email": "nyouellr@slideshare.net", "gender": "Female" },
{ "id": 29, "name": "Dyan", "email": "ddarrigrands@unc.edu", "gender": "Female" },
{ "id": 30, "name": "Wileen", "email": "wstovest@bbb.org", "gender": "Female" },
{ "id": 31, "name": "Hamel", "email": "hjellettu@tmall.com", "gender": "Male" },
{ "id": 32, "name": "Monique", "email": "mbourgeoisv@tripadvisor.com", "gender": "Female" },
{ "id": 33, "name": "Moina", "email": "meadyw@friendfeed.com", "gender": "Female" },
{ "id": 34, "name": "Cristina", "email": "cdawsonx@timesonline.co.uk", "gender": "Bigender" },
{ "id": 35, "name": "Marline", "email": "mhugoy@ibm.com", "gender": "Female" },
{ "id": 36, "name": "Miner", "email": "mtousyz@hatena.ne.jp", "gender": "Male" },
{ "id": 37, "name": "Rhodia", "email": "rroffe10@com.com", "gender": "Female" },
{ "id": 38, "name": "Wakefield", "email": "wmattiussi11@hud.gov", "gender": "Male" },
{ "id": 39, "name": "Charline", "email": "cshea12@paypal.com", "gender": "Female" },
{ "id": 40, "name": "Cherianne", "email": "clinnett13@yahoo.co.jp", "gender": "Female" },
{ "id": 41, "name": "Ulrick", "email": "ubailess14@mozilla.com", "gender": "Male" },
{ "id": 42, "name": "Boony", "email": "bbushell15@jiathis.com", "gender": "Male" },
{ "id": 43, "name": "Salaidh", "email": "sberthomier16@aol.com", "gender": "Female" },
{ "id": 44, "name": "Nevin", "email": "ncochrane17@amazon.com", "gender": "Agender" },
{ "id": 45, "name": "David", "email": "dsarah18@ibm.com", "gender": "Male" },
{ "id": 46, "name": "Jacki", "email": "jantonsson19@youku.com", "gender": "Female" },
{ "id": 47, "name": "Duky", "email": "dmckeeman1a@sitemeter.com", "gender": "Male" },
{ "id": 48, "name": "Mariam", "email": "mpentycross1b@stumbleupon.com", "gender": "Female" },
{ "id": 49, "name": "Bradney", "email": "btassaker1c@blogger.com", "gender": "Male" },
{ "id": 50, "name": "Sianna", "email": "sclucas1d@gravatar.com", "gender": "Female" }]

console.log(users.length)
for (user of users) {
    console.log(user.email)
}